DROP TABLE IF EXISTS recipes;

CREATE TABLE recipes (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title VARCHAR(512) NOT NULL,
    ingredients VARCHAR(512) NOT NULL,
    thumbnail VARCHAR(512)  
);

